NAME=	libft.a
cc=	cc 
CFLAGS=	-Wall -Wextra -Werror

AF=	ft_isalpha.c	\
ft_isdigit.c	\
ft_isalnum.c	\
ft_isascii.c	\
ft_toupper.c	\
ft_tolower.c	\
ft_isprint.c	\
ft_atoi.c	\
ft_strncmp.c	\
ft_bzero.c	\
ft_memset.c	\
ft_memcpy.c	\
ft_memmove.c	\
ft_memchr.c	\
ft_memcmp.c	\
ft_strlcpy.c	\
ft_strlcat.c	\
ft_strlen.c	\
ft_strchr.c	\
ft_strrchr.c	\
ft_calloc.c	\
ft_strnstr.c	\
ft_strdup.c	\
ft_substr.c	\
ft_strjoin.c	\
ft_strtrim.c	\
ft_split.c	\
ft_itoa.c	\
ft_strmapi.c	\
ft_striteri.c	\
ft_putchar_fd.c	\
ft_putstr_fd.c	\
ft_putendl_fd.c	\
ft_putnbr_fd.c	\

bonus=	ft_lstnew_bonus.c	\
ft_lstnew_bonus.c	\
ft_lstadd_front_bonus.c	\
ft_lstsize_bonus.c	\
ft_lstlast_bonus.c	\
ft_lstadd_back_bonus.c	\
ft_lstdelone_bonus.c	\
ft_lstclear_bonus.c	\
ft_lstiter_bonus.c	\

HLB=	$(AF:.c=.o)

BONUSO=	$(bonus:.c=.o)

all:	$(NAME)
	
$(NAME):	$(HLB)
	ar r $(NAME) $(HLB)
	
%.o : %.c
	$(cc) $(CFLAGS) -c  $?

 bonus :  $(BONUSO)
	ar r $(NAME) $(BONUSO)

clean:
	rm -f $(HLB) $(BONUSO)

fclean:	clean
	rm -f $(NAME)

re: fclean all
